// Generated by gencpp from file xingt_msgs/encoder_coder.msg
// DO NOT EDIT!


#ifndef XINGT_MSGS_MESSAGE_ENCODER_CODER_H
#define XINGT_MSGS_MESSAGE_ENCODER_CODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace xingt_msgs
{
template <class ContainerAllocator>
struct encoder_coder_
{
  typedef encoder_coder_<ContainerAllocator> Type;

  encoder_coder_()
    : header()
    , ecoder_data(0.0)  {
    }
  encoder_coder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ecoder_data(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _ecoder_data_type;
  _ecoder_data_type ecoder_data;





  typedef boost::shared_ptr< ::xingt_msgs::encoder_coder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xingt_msgs::encoder_coder_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_coder_

typedef ::xingt_msgs::encoder_coder_<std::allocator<void> > encoder_coder;

typedef boost::shared_ptr< ::xingt_msgs::encoder_coder > encoder_coderPtr;
typedef boost::shared_ptr< ::xingt_msgs::encoder_coder const> encoder_coderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xingt_msgs::encoder_coder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xingt_msgs::encoder_coder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xingt_msgs::encoder_coder_<ContainerAllocator1> & lhs, const ::xingt_msgs::encoder_coder_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ecoder_data == rhs.ecoder_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xingt_msgs::encoder_coder_<ContainerAllocator1> & lhs, const ::xingt_msgs::encoder_coder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xingt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xingt_msgs::encoder_coder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xingt_msgs::encoder_coder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xingt_msgs::encoder_coder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xingt_msgs::encoder_coder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xingt_msgs::encoder_coder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xingt_msgs::encoder_coder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xingt_msgs::encoder_coder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b427f1933e5117154d51519851bf4287";
  }

  static const char* value(const ::xingt_msgs::encoder_coder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb427f1933e511715ULL;
  static const uint64_t static_value2 = 0x4d51519851bf4287ULL;
};

template<class ContainerAllocator>
struct DataType< ::xingt_msgs::encoder_coder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xingt_msgs/encoder_coder";
  }

  static const char* value(const ::xingt_msgs::encoder_coder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xingt_msgs::encoder_coder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n"
"float64 ecoder_data\n"
"# float64 init_theta;\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::xingt_msgs::encoder_coder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xingt_msgs::encoder_coder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ecoder_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_coder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xingt_msgs::encoder_coder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xingt_msgs::encoder_coder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ecoder_data: ";
    Printer<double>::stream(s, indent + "  ", v.ecoder_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XINGT_MSGS_MESSAGE_ENCODER_CODER_H
