// Generated by gencpp from file xingt_msgs/laser_range.msg
// DO NOT EDIT!


#ifndef XINGT_MSGS_MESSAGE_LASER_RANGE_H
#define XINGT_MSGS_MESSAGE_LASER_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace xingt_msgs
{
template <class ContainerAllocator>
struct laser_range_
{
  typedef laser_range_<ContainerAllocator> Type;

  laser_range_()
    : header()
    , distence()  {
    }
  laser_range_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distence(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _distence_type;
  _distence_type distence;





  typedef boost::shared_ptr< ::xingt_msgs::laser_range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xingt_msgs::laser_range_<ContainerAllocator> const> ConstPtr;

}; // struct laser_range_

typedef ::xingt_msgs::laser_range_<std::allocator<void> > laser_range;

typedef boost::shared_ptr< ::xingt_msgs::laser_range > laser_rangePtr;
typedef boost::shared_ptr< ::xingt_msgs::laser_range const> laser_rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xingt_msgs::laser_range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xingt_msgs::laser_range_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xingt_msgs::laser_range_<ContainerAllocator1> & lhs, const ::xingt_msgs::laser_range_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.distence == rhs.distence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xingt_msgs::laser_range_<ContainerAllocator1> & lhs, const ::xingt_msgs::laser_range_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xingt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xingt_msgs::laser_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xingt_msgs::laser_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xingt_msgs::laser_range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xingt_msgs::laser_range_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xingt_msgs::laser_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xingt_msgs::laser_range_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xingt_msgs::laser_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e748a0d3c3338d7323b5506f7db1a7af";
  }

  static const char* value(const ::xingt_msgs::laser_range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe748a0d3c3338d73ULL;
  static const uint64_t static_value2 = 0x23b5506f7db1a7afULL;
};

template<class ContainerAllocator>
struct DataType< ::xingt_msgs::laser_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xingt_msgs/laser_range";
  }

  static const char* value(const ::xingt_msgs::laser_range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xingt_msgs::laser_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64[]  distence\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::xingt_msgs::laser_range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xingt_msgs::laser_range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct laser_range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xingt_msgs::laser_range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xingt_msgs::laser_range_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distence[]" << std::endl;
    for (size_t i = 0; i < v.distence.size(); ++i)
    {
      s << indent << "  distence[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.distence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XINGT_MSGS_MESSAGE_LASER_RANGE_H
