// Generated by gencpp from file xingt_msgs/motor_angle.msg
// DO NOT EDIT!


#ifndef XINGT_MSGS_MESSAGE_MOTOR_ANGLE_H
#define XINGT_MSGS_MESSAGE_MOTOR_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace xingt_msgs
{
template <class ContainerAllocator>
struct motor_angle_
{
  typedef motor_angle_<ContainerAllocator> Type;

  motor_angle_()
    : header()
    , motorAngle()  {
    }
  motor_angle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motorAngle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _motorAngle_type;
  _motorAngle_type motorAngle;





  typedef boost::shared_ptr< ::xingt_msgs::motor_angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xingt_msgs::motor_angle_<ContainerAllocator> const> ConstPtr;

}; // struct motor_angle_

typedef ::xingt_msgs::motor_angle_<std::allocator<void> > motor_angle;

typedef boost::shared_ptr< ::xingt_msgs::motor_angle > motor_anglePtr;
typedef boost::shared_ptr< ::xingt_msgs::motor_angle const> motor_angleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xingt_msgs::motor_angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xingt_msgs::motor_angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xingt_msgs::motor_angle_<ContainerAllocator1> & lhs, const ::xingt_msgs::motor_angle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.motorAngle == rhs.motorAngle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xingt_msgs::motor_angle_<ContainerAllocator1> & lhs, const ::xingt_msgs::motor_angle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xingt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xingt_msgs::motor_angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xingt_msgs::motor_angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xingt_msgs::motor_angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xingt_msgs::motor_angle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xingt_msgs::motor_angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xingt_msgs::motor_angle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xingt_msgs::motor_angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "113821ca482db708486595036ae6c738";
  }

  static const char* value(const ::xingt_msgs::motor_angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x113821ca482db708ULL;
  static const uint64_t static_value2 = 0x486595036ae6c738ULL;
};

template<class ContainerAllocator>
struct DataType< ::xingt_msgs::motor_angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xingt_msgs/motor_angle";
  }

  static const char* value(const ::xingt_msgs::motor_angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xingt_msgs::motor_angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64[]  motorAngle\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::xingt_msgs::motor_angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xingt_msgs::motor_angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motorAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xingt_msgs::motor_angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xingt_msgs::motor_angle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motorAngle[]" << std::endl;
    for (size_t i = 0; i < v.motorAngle.size(); ++i)
    {
      s << indent << "  motorAngle[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.motorAngle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XINGT_MSGS_MESSAGE_MOTOR_ANGLE_H
